<#
.SYNOPSIS
    Sets up the Cloudflare Tunnel URL for the React frontend.
    
.DESCRIPTION
    This script updates the .env.local file with the Cloudflare Tunnel URL
    for your backend API. Use this after starting your backend tunnel.
    
.PARAMETER TunnelUrl
    The Cloudflare Tunnel URL (e.g., https://random-words.trycloudflare.com)
    
.EXAMPLE
    .\Set-TunnelUrl.ps1 -TunnelUrl "https://random-words.trycloudflare.com"
    
.EXAMPLE
    .\Set-TunnelUrl.ps1
    # Will prompt for the URL
#>

param(
    [Parameter(Mandatory=$false)]
    [string]$TunnelUrl
)

$ErrorActionPreference = "Stop"

# Colors
function Write-ColorOutput($ForegroundColor) {
    $fc = $host.UI.RawUI.ForegroundColor
    $host.UI.RawUI.ForegroundColor = $ForegroundColor
    if ($args) {
        Write-Output $args
    }
    $host.UI.RawUI.ForegroundColor = $fc
}

Write-Host ""
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host "  ASU Dorms - Set Cloudflare Tunnel URL" -ForegroundColor Cyan
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host ""

# Get the script's directory and navigate to project root
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$projectRoot = Split-Path -Parent $scriptDir

Write-Host "Project root: $projectRoot" -ForegroundColor Gray

# Prompt for URL if not provided
if (-not $TunnelUrl) {
    Write-Host "Enter your Cloudflare Tunnel URL" -ForegroundColor Yellow
    Write-Host "(e.g., https://random-words.trycloudflare.com)" -ForegroundColor Gray
    Write-Host ""
    $TunnelUrl = Read-Host "Tunnel URL"
}

# Validate URL
if (-not $TunnelUrl) {
    Write-Host "ERROR: No URL provided." -ForegroundColor Red
    exit 1
}

# Ensure URL starts with https://
if (-not $TunnelUrl.StartsWith("https://") -and -not $TunnelUrl.StartsWith("http://")) {
    $TunnelUrl = "https://$TunnelUrl"
}

# Remove trailing slash and /swagger if present
$TunnelUrl = $TunnelUrl.TrimEnd('/')
$TunnelUrl = $TunnelUrl -replace '/swagger$', ''
$TunnelUrl = $TunnelUrl -replace '/api$', ''

Write-Host ""
Write-Host "Setting API URL to: $TunnelUrl" -ForegroundColor Green

# Create/Update .env.local
$envLocalPath = Join-Path $projectRoot ".env.local"
$envContent = @"
# ASU Dorms Management System - Local Environment Override
# This file is gitignored and contains your local configuration
# Generated by Set-TunnelUrl.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Cloudflare Tunnel API URL
VITE_API_URL=$TunnelUrl
"@

Set-Content -Path $envLocalPath -Value $envContent -Encoding UTF8
Write-Host "Updated: $envLocalPath" -ForegroundColor Green

# Also update index.html runtime config if needed
$indexPath = Join-Path $projectRoot "index.html"
if (Test-Path $indexPath) {
    $indexContent = Get-Content $indexPath -Raw
    
    # Update the runtime config baseUrl
    $pattern = "baseUrl:\s*'[^']*'"
    $replacement = "baseUrl: '$TunnelUrl'"
    
    if ($indexContent -match $pattern) {
        $indexContent = $indexContent -replace $pattern, $replacement
        Set-Content -Path $indexPath -Value $indexContent -Encoding UTF8
        Write-Host "Updated: index.html (runtime config)" -ForegroundColor Green
    }
}

Write-Host ""
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host "  Configuration Complete!" -ForegroundColor Green
Write-Host "=============================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Restart your React dev server: npm run dev" -ForegroundColor White
Write-Host "2. Your frontend will now connect to: $TunnelUrl" -ForegroundColor White
Write-Host ""
Write-Host "To build for production:" -ForegroundColor Yellow
Write-Host "   npm run build" -ForegroundColor White
Write-Host ""
